version: '3.9'

services:
  node:
    image: kademliabookmarks
    build:
      context: .
      dockerfile: ./Dockerfile
    networks:
      - kademlia_net
    deploy:
      mode: replicated
      replicas: 4
networks:
  kademlia_net:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.16.238.0/24
          gateway: 172.16.238.1